name: KoaliCRAFTUtils
version: 1.1
main: ch.hekates.kcutils.koalicraftutils.KoaliCraft
api-version: 1.18
authors: [ Hekates ]

commands:
  rules:
    permission: "rules.use"
  flypad:
    permission: kc.team
  grave:
  stats:
  statistics:
  status:
    usage: "Usage: /<command> <status>"
  db:
  enderchest:
    aliases: [ec]
    permission: kc.ec
  invsee:
    aliases: [inv]
    permission: kc.team
  enderdrop:
    aliases: [ed]
    permission: kc.enderdrop


permissions:
  kc.plot:
    default: op
  kc.team:
    default: op
  kc.enderdrop:
    default: op
