name: KoaliCRAFTUtils
version: 1.1
main: ch.hekates.kcutils.koalicraftutils.KoaliCraft
api-version: 1.17
authors: [ Hekates ]

commands:
  rules:
    permission: "rules.use"
  report:
    permission: "report.use"
  flypad:
    permission: kc.team
  grave:
  stats:
  statistics:
  status:
    usage: "Usage: /<command> <status>"

permissions:
  kc.plot:
    default: op
  kc.team:
    default: op
